version: '3'
services: 
    mongo:
        image: mongo
        container_name: mongo    
        networks: 
            - agenda-network
    
    node:
        image: node
        container_name: node
        networks:
            - agenda-network
        ports: 
            - "8081:3000"
        depends_on:
            - "mongo"
        volumes:
          - ./server:/api
        working_dir: /api
        command: npm start

networks: 
    agenda-network: 
        driver: bridge

