version: '3'
services: 
    mongo:
        image: mongo
        container_name: mongo    
        networks: 
            - agenda-network
    
    node:
        image: node
        container_name: node
        networks:
            agenda-network:
                ipv4_address: 172.19.0.5
        ports: 
            - 3000:3000
        depends_on:
            - "mongo"
        volumes:
            - ./server:/api
        working_dir: /api
        command: bash -c "npm i -g nodemon && npm i && npm start"

    front:
        image: node
        container_name: front
        networks:
            agenda-network:
                ipv4_address: 172.19.0.6
        ports:
            - 8080:8080
        depends_on:
            - node
        working_dir: /app
        volumes:
            - ./client:/app
        command: bash -c "npm i && npm start"

networks: 
    agenda-network: 
        driver: bridge
        ipam:
         config:
           - subnet: 172.19.0.0/16